#!/usr/bin/env node

var fs = require('fs');
var path = require('path');
var program = require('commander');
var userhome = require('userhome');

if (!fs.existsSync(userhome('.lws.json'))) {
	require('../lib/config').init();
}

program
	.version(require('../package.json').version)
	.command('add', 'Add an object to the database.  Can be called with arguments (user, role, site, etc.), or can be called on its own for an interactive adding process.\n')
	.command('get', 'Get an object from the database.  Can be called with arguments (user, role, site, etc.), or can be called on its own for an interactive getting process.\n')
	.command('config', 'Configure LWS.');

// Some logic that searches global dirs and finds modules
// Each calls 'program.command()'

program.parse(process.argv);

if (!process.argv.slice(2).length) {
	program.outputHelp();
}
