#!/usr/bin/env node

var fs = require('fs');
var path = require('path');
var program = require('commander');
var userhome = require('userhome');

if (!fs.existsSync(userhome('.lws.json'))) {
	require('../lib/config').init();
}

program
	.version(require('../package.json').version)
	.command('add', 'Add an object to the database.\n\t\t   Can be called with arguments (user, role, site, etc.), or can be called on its own for an interactive adding process.\n')
	.command('gu <userInfo>', 'get-user | Gets a user from the database based on userId, screenName, or emailAddress.')
	.command('gr <roleInfo>', 'get-role | Gets a role from the database based on roleId or roleName.')
	.command('config', 'Configure LWS.');

// Some logic that searches global dirs and finds modules
// Each calls 'program.command()'

program.parse(process.argv);

if (!process.argv.slice(2).length) {
	program.outputHelp();
}
