#!/usr/bin/env node

var async = require('async');
var program = require('commander');
var utils = require('../lib/utils');

program
	.option('-s, --silly', 'Generate a silly name. [optional]')
	.parse(process.argv);

var numberOfUsers = Number(program.args[0]) || 1;
var bar = utils.getProgressBar(numberOfUsers);

utils.statusMessage(numberOfUsers, 'user');

async.timesSeries(
	numberOfUsers,
	function(n, callback) {
		var person = utils.generateUserInfo();

		require('../actions/add-user.js')(person.firstName, person.lastName, person.screenName, person.emailAddress, function(error, response) {
			if (!error) {
				bar.tick();
				callback(null, response);
			}
		})
	},
	function(error, results) {
		if (!error) {
			for (var i = 0, length = results.length; i < length; i++) {
				console.log('');
				console.log('New User:');
				utils.logJSON(JSON.parse(results[i]));
				console.log('');
			}

			console.log('Successfully added', + results.length + ' new users.');
		}
	}
);