#!/usr/bin/env node

var _ = require('lodash');
var program = require('commander');

program
	.command('user [userInfo...]')
	.alias('users')
	.description('Gets one or more users from the database. If no user info is provided, it will return all users.')
	.action(function(userInfo) {
		require('./get/user')(userInfo);
	});

program
	.command('role <roleInfo...>')
	.alias('roles')
	.description('Gets one or more roles from the database. If no role info is provided, it will return all roles.')
	.action(function(roleInfo) {
		require('./get/role')(roleInfo);
	});

program.parse(process.argv);
