#!/usr/bin/env node

var path = require('path');
var home = process.env.HOME;
var fs = require('fs');
var nconf = require('nconf');
var inquirer = require('inquirer');

var configFilePath = path.join(home, '.lws/config.json');

nconf.argv()
	.env()
	.file({ file: configFilePath });

nconf.set('username', 'test@liferay.com');
nconf.set('password', 'test');
nconf.set('domain', 'localhost');
nconf.set('port', '8080');
nconf.set('portalVersion', 'master');


fs.readFile(configFilePath, function (err, data) {
	console.dir(JSON.parse(data.toString()))
});

nconf.save(function (err) {
	fs.readFile(configFilePath, function (err, data) {
		console.dir(JSON.parse(data.toString()))
	});
});