#!/usr/bin/env node

var _ = require('lodash');
var program = require('commander');

var utils = require('../lib/utils');

var commands = utils.getCommands('get');

program
	.command('user [userInfo...]')
	.alias('u')
	.description('Gets one or more users from the database. If no user info is provided, it will return all users.')
	.action(function(userInfo) {
		commands.getUser(userInfo);
	});

program
	.command('role <roleInfo...>')
	.alias('r')
	.description('Gets one or more roles from the database. Role id or name is required.')
	.action(function(roleInfo) {
		commands.getRole(roleInfo);
	});

program.parse(process.argv);

if (!process.argv.slice(2).length) {
	program.outputHelp();
}
