#!/usr/bin/env node

var async = require('async');
var program = require('commander');
var utils = require('../lib/utils');
var getRoleActionRouter = require('../method-routers/get-role-router');

program.parse(process.argv);

roleInfo = program.args;

if (!roleInfo.length) {
	console.error('Please provide role info.');
}

async.timesSeries(
	roleInfo.length,
	function(n, asyncCallback) {
		var getRoleAction = getRoleActionRouter(roleInfo[n]);

		require(getRoleAction)(roleInfo[n], function(error, response) {
			if (!error) {
				asyncCallback(null, response);
			}
		});
	},
	function(error, results) {
		if (!error) {
			for (var i = 0, length = results.length; i < length; i++) {
				console.log('');
				console.log('Got Role:');
				utils.logJSON(JSON.parse(results[i]));
				console.log('');
			}
		}
	}
);