var Method = require('../Method');

module.exports = function(name, type) {
	var role = {
		className: null,
		classPK: 0,
		name: name,
		titleMap: JSON.stringify({
			"en_US": name
		}),
		descriptionMap: JSON.stringify({
			"en_US": "Generated by LWS."
		}),
		type: type,
		subtype: null
	};

	var method = new Method('/role/add-role', role);

	return method.invoke();
};