var Method = require('../Method');

module.exports = function(name, callback) {
	var group =  {
		parentGroupId: 0,
		liveGroupId: 0,
		nameMap: JSON.stringify({"en_US": name}),
		descriptionMap: JSON.stringify({"en_US": "Generated by LWS"}),
		type: 1,
		manualMembership: true,
		membershipRestriction: 0,
		friendlyURL: '',
		site: true,
		inheritContent: false,
		active: true
	};

	var method = new Method('/group/add-group', group);

	method.invoke(callback);
}