var Method = require('../Method');

module.exports = function(groupId, name, parentLayoutId) {
	var layout =  {
		groupId: groupId,
		privateLayout: false,
		parentLayoutId: parentLayoutId,
		name: name,
		title: name,
		description: 'Generated by LWS',
		type: 'portlet',
		hidden: false,
		friendlyURL: ''
	};

	var method = new Method('/layout/add-layout', layout);

	return method.invoke();
};