var utils = require('../utils');

var Method = utils.getMethodClass();

module.exports = function(name, type, callback) {
	var role = {
		name: name,
		titleMap: JSON.stringify({
			"en_US": name
		}),
		descriptionMap: JSON.stringify({
			"en_US": "Generated by LWS."
		}),
		type: type
	};

	var method = new Method('/role/add-role', role);

	method.invoke(callback);
}