var generatorUtil = require('./utils/generatorUtil');

function get() {
	// Re-used generated data
	var personObject = generatorUtil.generateUserInfo();
	var roleName = generatorUtil.generateRoleName();

	// Re-used Display Keys Omissions
	var userOmitFromResultsDisplayKeys = ['createDate', 'facebookId', 'greeting', 'languageId', 'ldapServerId', 'modifiedDate', 'mvccVersion', 'portraitId', 'timeZoneId', 'uuid'];

	var DEFAULT_VALUES = {
		Group: {
			'add-group': {
				params: {
					nameMap: JSON.stringify({ "en_US": generatorUtil.generateGroupName() }),
					descriptionMap: JSON.stringify({ "en_US": "Generated by LWS" }),
					type: 1,
					manualMembership: true,
					site: true,
					active: true
				},
				requiredParams: []
			}
		},
		Organization: {
			'add-organization': {
				params: {
					name: generatorUtil.generateOrganizationName(),
					statusId: 12017,
					type: 'organization'
				},
				requiredParams: []
			}
		},
		Role: {
			'add-role': {
				params: {
					descriptionMap: JSON.stringify({ "en_US": "Generated by LWS." }),
					name: roleName,
					titleMap: JSON.stringify({ "en_US": roleName }),
					type: 1,
				},
				requiredParams: []
			},
			'add-user-roles': {
				params: {},
				requiredParams: ['userId', 'roleIds']
			},
			'delete-role': {
				params: {},
				requiredParams: ['roleId']
			}
		},
		User: {
			'add-user': {
				params: {
					birthdayDay: 1,
					birthdayMonth: 1,
					birthdayYear: 1901,
					emailAddress: personObject.emailAddress,
					firstName: personObject.firstName,
					lastName: personObject.lastName,
					male: personObject.male,
					password1: 'test',
					password2: 'test',
					screenName: personObject.screenName
				},
				omitFromResultsDisplayKeys: userOmitFromResultsDisplayKeys,
				requiredParams: []
			},
			'add-role-users': {
				params: {},
				requiredParams: ['roleId',
				'userIds']
			},
			'get-company-users': {
				omitFromResultsDisplayKeys: userOmitFromResultsDisplayKeys
			}
		},
		UserGroup: {
			'add-user-group': {
				params: {
					name: generatorUtil.generateUserGroupName()
				},
				omitFromResultsDisplayKeys: ['createDate', 'modifiedDate', 'mvccVersion', 'parentUserGroupId', 'uuid', 'userName']
			}
		}
	};

	return DEFAULT_VALUES;
}

module.exports = get;