var Action = require('../lib/actionClass');

module.exports = function(groupId, name, parentLayoutId, callback) {
	var layout =  {
		groupId: groupId,
		privateLayout: false,
		parentLayoutId: parentLayoutId,
		name: name,
		title: name,
		description: 'Generated by LWS',
		type: 'portlet',
		hidden: false,
		friendlyURL: ''
	};

	var action = new Action('/layout/add-layout', layout);

	action.doAction(callback);
}