var Chance = require('chance');
var chance = new Chance();

function get() {
	// Re-used generated data
	var GROUP_NAME = 'LWS Group: ' + chance.capitalize(chance.word());

	// Re-used Display Keys Omissions
	var OMIT_KEYS = ['name', 'uuid', 'description', 'mvccVersion', 'liveGroupId', 'creatorUserId', 'remoteStagingGroupCount', 'membershipRestriction', 'descriptionCurrentValue', 'typeSettings'];

	var Group = {
		'add-group': {
			omitFromResultsDisplayKeys: OMIT_KEYS,
			params: {
				active: true,
				description: "Generated by LWS",
				descriptionMap: JSON.stringify({ "en_US": "Generated by LWS" }),
				manualMembership: true,
				name: GROUP_NAME,
				nameMap: JSON.stringify({ "en_US": GROUP_NAME }),
				site: true,
				type: 1
			},
			requiredParams: []
		},
		'get-groups': {
			omitFromResultsDisplayKeys: OMIT_KEYS,
			params: {
				site: true
			},
			requiredParams: []
		}
	};

	return Group;
}

// Template
var template = {

'method-name': {
	omitFromResultsDisplayKeys: [],
	params: {},
	requiredParams: []
}

};

module.exports = get;