var Chance = require('chance');
var chance = new Chance();

function get() {
	// Re-used generated data
	var roleName = 'LWS Role: ' + chance.capitalize(chance.word());

	var OMIT_KEYS = ['description', 'createDate', 'descriptionCurrentValue', 'modifiedDate', 'mvccVersion', 'title', 'uuid'];

	// Method configuration object
	var Role = {
		'add-role': {
			omitFromResultsDisplayKeys: OMIT_KEYS,
			params: {
				descriptionMap: JSON.stringify({ "en_US": "Generated by LWS." }),
				name: roleName,
				titleMap: JSON.stringify({ "en_US": roleName }),
				type: 1,
			},
			requiredParams: []
		},
		'add-user-roles': {
			omitFromResultsDisplayKeys: [],
			params: {},
			requiredParams: ['userId', 'roleIds']
		},
		'delete-role': {
			omitFromResultsDisplayKeys: [],
			params: {},
			requiredParams: ['roleId']
		},
		'get-role': {
			omitFromResultsDisplayKeys: OMIT_KEYS,
			params: {},
			requiredParams: ['name']
		},
		'get-roles': {
			omitFromResultsDisplayKeys: OMIT_KEYS,
			params: {},
			requiredParams: []
		}
	};

	return Role;
}

// Template
var template = {

'method-name': {
	omitFromResultsDisplayKeys: [],
	params: {},
	requiredParams: []
}

};

module.exports = get;